SELECT ?ville ?codePostal (COUNT(?inspection) AS ?count)
WHERE {
  ?inspection a <https://www.example.org/Inspection>.
  ?inspection <https://www.example.org/evaluation> ?synthese.
  
  ?inspection <https://schema.org/LocalBusiness> ?etablissement.
  ?etablissement <https://schema.org/GeoCoordinates> ?coordinates.
  ?coordinates <https://schema.org/PostalAddress> ?adresse.
  ?adresse <https://schema.org/postalCode> ?codePostal;
    <https://schema.org/addressLocality> ?ville.  

  FILTER (?synthese IN ("Satisfaisant", "Très satisfaisant"))
} GROUP BY ?ville ?codePostal HAVING (COUNT(?inspection) > 2) 
ORDER BY COUNT(?inspection)